name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
      POSTGRES_DOCKER_PORT: ${{ secrets.POSTGRES_DOCKER_PORT }}
      SPRING_DOCKER_PORT: ${{ secrets.SPRING_DOCKER_PORT }}
      DEBUG_PORT: ${{ secrets.DEBUG_PORT }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}

      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

      PAYMENT_SUCCESS_URL: ${{ secrets.PAYMENT_SUCCESS_URL }}
      PAYMENT_CANCEL_URL: ${{ secrets.PAYMENT_CANCEL_URL }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
